### ISSUE TITLE
saturation-drag indicator stuck at same horizontal position

### ISSUE THREAD

**Issue by flyon** [zippyui/react-color-picker#10]
The little while ball that indicates where in the square the color is always remains on the same x-coordinate, but it DOES move in y-coordinate.

When I click for example in the topleft corner the right color comes in the onDrag handler (something close to ffffff) and the right color goes into ```<ColorPicker value={rightValueHere} />``` but the representation seems stuck

**Comment by radubrehar** [comment]
Can you have a look at `3.0.0`, just published on npm? It also supports React 0.14

**Comment by dev-zippyui** [comment]
Our latest version, `4.0.1` includes a fix for this, so closing as no longer reproducible
