### ISSUE TITLE
Two copies of React on page

### ISSUE THREAD

**Issue by essekia** [zippyui/react-color-picker#13]
Hi,

This is most probably a mis-configuration at my side. But I get these 2 errors:

**Warning:**
" React can't find the root component node for data-reactid value `.0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time. "

**Error:**
"Uncaught TypeError: Cannot read property 'firstChild' of undefined"

**This is my module code:**

```
define(['react', 'vendor/react-color-picker'], function(React, ColorPicker) {

    var myColorPicker = React.createClass({
        render: function() {
            return React.createElement(ColorPicker, {
                value: '157dec'
            });
        }
    });

    return myColorPicker;
});

```
I used the /dist/react-color-picker.js file.

Can you point me where I am going wrong?

**Comment by prewk** [comment]
Not a simple solution to your problem but you should _really_ look into using a proper js bundler like webpack (or browserify etc), the uncertainty of your surrounding environment probably contains the source of your error.

**Comment by essekia** [comment]
Thanks @prewk . After asking here, I am now using web pack and everything works fine!

**Comment by prewk** [comment]
Great, glad to help :)

**Comment by radubrehar** [comment]
Good job!

**Comment by gidili** [comment]
Having the exact same issue. I am using react of course for a bunch of other components and when I require react-color-picker I get the exact same error. 

@essekia any pointers on how you solved the problem with webpack? Are you rebuilding from sources or resolving in the frontend? Any help appreciated.

**Comment by essekia** [comment]
@gidili I used webpack to load all dependencies, and removed requireJS and I also found that I had loaded another copy of react on the browser directly using the <script> tag.

Hope this helps.

**Comment by gidili** [comment]
@essekia yes thanks. Unfortunately I cannot use webpack as a loader in my project right now (big project, yadda yadda yadda). 

I wonder if there is a way for me to solve this some other way, maybe rebuild react-color-picker so that on require('react') it uses the version of react I expose in my require paths instead of adding another one. like many other react components I am importing do.

Any pointer appreciated!

**Comment by dev-zippyui** [comment]
Not directly related to `react-color-picker`, so we're closing this.
