### ISSUE TITLE
Making the hue spectrum usable close to #ffffff and #000000

### ISSUE THREAD

**Issue by prewk** [zippyui/react-color-picker#14]
Is it possible to make the hue spectrum a bit more draggable when close to black and white?

Drag the saturation spectrum to top left or bottom right, and then try to drag the hue spectrum around: http://jslog.com/react-color-picker/

I understand the problem, the color picker just reacts to the data, and there's no notion of "green black" or "green white" etc, but it would help end users who think something's wrong when it's "stuck".

**Comment by radubrehar** [comment]
Yes, I thought of a solution to this, will try to implement it! Thanks for reporting

**Comment by prewk** [comment]
Awesome! Any progress?

**Comment by prewk** [comment]
@radubrehar Sorry for spamming but I would love a solution to this. Did your solution work?

**Comment by prewk** [comment]
I tried doing it myself, but to no avail. Your code style is too alien to me :) Any pointers?

**Comment by dev-zippyui** [comment]
This has been fixed in `4.0.1`.
Feel free to reopen if you can repro it with the new version

**Comment by prewk** [comment]
FYI http://jslog.com/react-color-picker/ still has this problem. Not upgraded?

**Comment by dev-zippyui** [comment]
Yep, not upgraded.
