### ISSUE TITLE
The hue slider doesn't work if the initial color is #000 or #fff

### ISSUE THREAD

**Issue by alexcojocaru** [zippyui/react-color-picker#15]
If the colour is #000 or #fff, clicking on the hue slider does not have any effect.

That is because both these colors have the saturation equal to 0, and the updateColor method in HueSpectrum does not reset the saturation. For all the colours on the hue slider, the saturation is 1.

I will submit a merge request to fix this issue soon.

**Comment by alexcojocaru** [comment]
Here's the merge request to fix this issue:
https://github.com/zippyui/react-color-picker/pull/16

**Comment by sisiguo** [comment]
+1 To have this fixed with the merge request above.

**Comment by dev-zippyui** [comment]
We just fixed this in `4.0.0`. Thanks for reporting!
