### ISSUE TITLE
Unknown props in ColorPicker

### ISSUE THREAD

**Issue by Becherman** [zippyui/react-color-picker#19]
Hi! I have 2 color-picker components on my page. Before i update react to 15.2.1 everything is being normal. But after updating i see this "Warning: Unknown props `saturationWidth`, `saturationHeight`, `hueWidth`, `defaultColor`, `hueHeight`, `hueMargin` on <div> tag. Remove these props from the element". I have tried put my props like key and value and with spread operator but it did not help. May be someone have solution for this?

**Comment by radubrehar** [comment]
This is an issue with React 15.2, which introduced new warnings. We'll come up with a fix on this.

**Comment by Becherman** [comment]
Oh, thank you! I will waiting news about this issues!

**Comment by dev-zippyui** [comment]
We just released `4.0.0` with the fixes & updates to make the component run smoothly for React `15.2.0`.
Please have a look!
Thanks for reporting & patience.

**Comment by Becherman** [comment]
Hello! Today i'm checked your last realise and may say that everything work wonderfully! Thank you!
