### ISSUE TITLE
Server-side rendering is broken

### ISSUE THREAD

**Issue by xavimb** [zippyui/react-color-picker#20]
The newest version of `drag-helper` uses the `window` object, so it breaks server-side rendering.
This is the error I get when I try to start the server:

```
ReferenceError: window is not defined
```

 As `drag-helper` is a library that is only meant to use on the client side and not on the server side, I think there should be some condition to exclude/mock the library if there's no DOM available.

**Comment by radubrehar** [comment]
Or a solution would be to include `jsdom` in your node environment.

**Comment by dev-zippyui** [comment]
Have a look at our `4.0.0`, just released on npm.
