### ISSUE TITLE
index.css file is JS on 4.0.0

### ISSUE THREAD

**Issue by chevin99** [zippyui/react-color-picker#21]
I upgraded to 4.0.0 and noticed this file here is JS, not CSS: https://github.com/zippyui/react-color-picker/blob/master/index.css

Is that intended?  It's causing the webpack build to fail because it's expecting CSS, not JS.

![image](https://cloud.githubusercontent.com/assets/7562346/17154754/977c77c2-533f-11e6-9e11-b973002af052.png)

**Comment by dev-zippyui** [comment]
Thanks for catching that!
Upgrade to `4.0.1` and this should be fixed.

**Comment by chevin99** [comment]
Thanks @dev-zippyui! But now there's a new problem:

When I use v3.1.0,  I render only this: `<ColorPicker value="#abc507"/>` and it works fine.  But I can't get that or anything else to work on v4.0.1.  I get this error:

`Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Comment by dev-zippyui** [comment]
We've had a major version bump, and moved from commonjs exports to es6 modules.

So, if you're still using commonjs requires, you have to do the following:

```jsx
var ColorPicker = require('react-color-picker').default
//or, for HueSpectrum
var HueSpectrum = require('react-color-picker').HueSpectrum
```

**Comment by chevin99** [comment]
Beautiful, it works.  Thanks!
