### ISSUE TITLE
Receiving TypeError: (0 , _reactClass.autoBind) is not a function error after upgrading to latest react (15.3.0)

### ISSUE THREAD

**Issue by mairh** [zippyui/react-color-picker#23]
I assume it is coming from this line https://github.com/zippyui/react-color-picker/blob/master/src/index.js#L18

<img width="865" alt="screen shot 2016-08-08 at 15 49 08" src="https://cloud.githubusercontent.com/assets/4072250/17480259/ad30d5b4-5d7f-11e6-81b9-e10abe86667b.png">

**Comment by dev-zippyui** [comment]
Thanks for catching that! Fixed in `4.0.2`, just released on npm
