### ISSUE TITLE
component not working due to React.createElement warning

### ISSUE THREAD

**Issue by sisiguo** [zippyui/react-color-picker#24]
Trying to update to `4.0.0` and I now get the following error when the color picker is rendered which makes the color picker unusable:
`warning.js:45 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of ...`.

Worked previously using version `3.1.0`.

**Comment by dev-zippyui** [comment]
Make sure you either `import` the picker, or require the `.default`

`import ColorPicker from 'react-color-picker'`
`var Picker = require('react-color-picker').default`

Starting 4.0.0 we exported things using es6 modules. That's why we made the major version bump.

**Comment by sisiguo** [comment]
Ah, I see now. Thanks for the prompt response and is there a page where version changes like this are documented?

**Comment by dev-zippyui** [comment]
Sure, just see https://github.com/zippyui/react-color-picker/releases
