### ISSUE TITLE
Mousedown and mouseup on controlled color-pickers

### ISSUE THREAD

**Issue by prewk** [zippyui/react-color-picker#6]
Hi, it's me again! ;)

I've got another little problem: http://oskarthornblad.se/colorpicker-problem/

Try mousedowning (holding the mouse button, duh) somewhere in the saturation picker. The marker doesn't go in the right place. Now let go of the mouse button - Bingo, it jumps to the right place.

The JS: http://oskarthornblad.se/colorpicker-problem/index.js

(It works when dragging)

**Comment by zippyui-react** [comment]
Will have a look into this. Thanks for reporting!

**Comment by prewk** [comment]
Any progress?

**Comment by gothy** [comment]
Commenting out this line fixes the issue. 
But I'm not sure this is an appropriate fix since I'm not an expert in this code :)
https://github.com/zippyui/react-color-picker/blob/master/src/SaturationSpectrum.jsx#L70

**Comment by prewk** [comment]
I finally tried it out and it didn't seem to fix the issue for me, unfortunately :)

@zippyui-react halp!

**Comment by radubrehar** [comment]
Can you confirm this is fixed in version `3.0.0`?

**Comment by prewk** [comment]
Confirmed.
