### ISSUE TITLE
Do not include normalize.css

### ISSUE THREAD

**Issue by davearata** [zippyui/react-color-picker#8]
Right now both index.styl and index.css include normalize.css. According to normalize.css documentation.

"No other styles should come before Normalize.css."

This means if react-color-picker stylesheet is loaded in after other css the included normalize.css styles can potentially override styles defined by the project.

The solution would be to remove normalize.css or make it a requirement that react-color-picker is the first css sheet loaded in the project.

**Comment by radubrehar** [comment]
Solved with `3.0.0`. Users should manually include normalize, if they need/want to. Thanks for the feedback
